services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: >-
      start-dev
      --import-realm
      --hostname-strict=false
      --hostname-strict-https=false
      --http-enabled=true
      --spi-realm-default-ssl-required=none
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
